### ISSUE TITLE
Wrong output for "Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding"

### ISSUE THREAD

**Issue by pnabbefeld** [marcelotduarte/cx_Freeze#1197]
Using Arch Linux with latest cx_freeze version from AUR.

I've noticed the bug "Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding" has been reported against several versions of cx_freeze and has been fixed in several others:
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

IMHO, there's more to fix than just that bug:
The error is reported as "ModuleNotFoundError" - but the problem seems to be the directory: either it isn't found, or some encoding has been detected, which isn't found in the directory.

So, it would be easier to find the cause for the bug, if the following data would be provided:
1. Which encoding has been detected?
2. Where did cx_freeze look for the encoding?

I'd guess, this would also be of interest for You, when people are asking for help with the encoding problem.

**Comment by marcelotduarte** [comment]
> Using Arch Linux with latest cx_freeze version from AUR.

link?

This error is not related to the encodings used but that it cannot load and starts the module itself. In general, this occurs because this is the first module loaded - or not loaded ;-)

When a user or packager builds python from sources and does not add --enable-shared this issue goes back.
And other similar situations.

If you provide more information about your system I can analyze it. Maybe related to recent changes in ArchLinux including LTO to the build. See PR #1132 

[cx_Freeze 6.8b2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8b2) has just been released.
Please, try it out and report. It has fixes for ArchLinux.
pip install cx-Freeze==6.8b2

**Comment by pnabbefeld** [comment]
According to PKGBUILD (of the package "python-cx-freeze-qfix" I'm using for installation), source is:
source=("https://github.com/marcelotduarte/cx_Freeze/archive/$pkgver/${pkgname%-qfix}-$pkgver.tar.gz"
        "export-dynamic.patch")

I'll try to "pip" and watch for the results. However, it seems some package is needed to resolve dependencies.

**Comment by marcelotduarte** [comment]
That patch fix partially the issue. So use the beta. 6.8b2 or 6.8b3
The dependencies see docs: https://cx-freeze.readthedocs.io/en/latest/installation.html

**Comment by pnabbefeld** [comment]
Okay, now found out how to install - usually i'm just using the packages ... ;)

But now I'm getting an error when building meshroom-git, and I'm not sure if this relates to cx-freeze or meshroom, but the errors are from cx-freeze output, so I'm starting here:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 1053, in _post_copy_hook
    relative = dependent_file.relative_to(source_dir)
  File "/usr/lib/python3.9/pathlib.py", line 929, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/usr/lib/libpcre.so.1' is not in the subpath of '/home/myuser/.local/lib/python3.9/site-packages/PySide2/Qt/lib' OR one path is relative and the other is absolute.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/peter/.cache/pikaur/build/meshroom-git/src/meshroom/setup.py", line 130, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/cx_Freeze/dist.py", line 447, in setup
    setuptools.setup(**attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
[...]
    self._post_copy_hook(
  File "/usr/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 1062, in _post_copy_hook
    relative = file.relative_to(targetdir)
  File "/usr/lib/python3.9/pathlib.py", line 929, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'build/exe.linux-x86_64-3.9/lib/PIL/libpcre.so.1' is not in the subpath of 'build/exe.linux-x86_64-3.9/lib/PySide2/Qt/lib' OR one path is relative and the other is absolute.
```

**Comment by marcelotduarte** [comment]
It is an issue of cx-freeze of the beta. I'm working on pathlib support.
https://aur.archlinux.org/packages/meshroom-git/ is the link of meshroom?
I have ArchLinux only on docker to test. How is the command to build it?

**Comment by pnabbefeld** [comment]
Yes, sorry - I'm also not much used to such builds ...

I'm using pikaur, so the command is "pikaur -Sa meshroom-git". Also, I'm first building alice-vision-git ("pikaur -Sa alice-vision-git"), as this is a dependency of meshroom-git. Also, instead of the "official" build of cx-freeze, I'm using python-cx-freeze-qfix from AUR, setting "pkgver=6.8b3" in PKGBUILD, skipping sha512sums and the patch command in line 25 (which doesn't work with 6.8b3).

So, as a result, I'm building:
1. Modified cx-freeze build;
2. alice-vision-git;
3. meshroom-git.

**Comment by marcelotduarte** [comment]
If you want to use 6.7 for now, you can adapt the patch
```
+++ b/export-dynamic.patch
@@ -0,0 +1,10 @@
+--- cx_Freeze-6.7/setup.py	2021-07-09 01:46:47.000000000 +0200
++++ cx_Freeze-6.7.new/setup.py	2021-08-03 17:27:53.413089371 +0200
+@@ -91,7 +91,4 @@
+             # fix a bug using macOS on Github Actions
+-            if "--with-lto" in get_config_var("CONFIG_ARGS"):
+-                extra_args.append("-flto")
+-                extra_args.append("-Wl,-export_dynamic")
+             if sys.platform != "darwin":
+                 extra_args.append("-s")
+                 extra_args.append("-Wl,-rpath,$ORIGIN/lib")
```
I changed manually... but the fix basically is removing 3 lines...

**Comment by pnabbefeld** [comment]
I think, rather than patching back and forth, I'll better wait for the next beta, as this will probably help both of us: You'll have some additional testing, and with the next release I'll probably no longer need the quick-fix from AUR.

**Comment by marcelotduarte** [comment]
I couldn't test with meshrom in the docker. It will take the time I don't have.
But another application managed to have similar errors and I believe I have solved the problem. Can you test?
pip install cx-Freeze==6.8b4

**Comment by pnabbefeld** [comment]
The path-matching problem seems to be solved.  But now I get a permission problem:

patchelf: open: Permission denied
Traceback (most recent call last):
  File "/home/peter/.cache/pikaur/build/meshroom-git/src/meshroom/setup.py", line 130, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/cx_Freeze/dist.py", line 447, in setup
    setuptools.setup(**attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
[...]
  File "/usr/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 1066, in _post_copy_hook
    self.patchelf.set_rpath(target, rpath)
  File "/usr/lib/python3.9/site-packages/cx_Freeze/patchelf.py", line 96, in set_rpath
    check_call(args)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['patchelf', '--force-rpath', '--set-rpath', '$ORIGIN/.', PosixPath('/home/peter/.cache/pikaur/build/meshroom-git/src/meshroom/build/exe.linux-x86_64-3.9/lib/libtk8.6.so')]' returned non-zero exit status 1.

libtk8.6.so is owned by my user account, so this should not cause the problem.

**Comment by marcelotduarte** [comment]
Can you put a `ls -l` of this lib directory?

> libtk8.6.so is owned by my user account, so this should not cause the problem.

But it think that in your system it is read-only, so I need to change the permission. I think it is related to issue #1171.

**Comment by pnabbefeld** [comment]
Yes, You're right - seems it has been too late yesterday.

ls -l /home/peter/.cache/pikaur/build/meshroom-git/src/meshroom/build/exe.linux-x86_64-3.9/lib/lib*.so
-rwxr-xr-x 1 peter users 3757176 30. Jun 12:22 /home/peter/.cache/pikaur/build/meshroom-git/src/meshroom/build/exe.linux-x86_64-3.9/lib/libpython3.9.so
-r-xr-xr-x 1 peter users 1587584 16. Jan 2021  /home/peter/.cache/pikaur/build/meshroom-git/src/meshroom/build/exe.linux-x86_64-3.9/lib/libtk8.6.so

Thank You for taking the time to fix this issue!

**Comment by marcelotduarte** [comment]
I managed to simulate the error and a solution (PR #1232).
Try to test using the following command:
`pip uninstall -y cx-freeze`
`pip install git+https://github.com/marcelotduarte/cx_Freeze.git@main`

If you need a new beta to test let me know.

> Thank You for taking the time to fix this issue!

You're welcome. When I said  'It will take the time I don't have', I was trying to say about learning how to use pikaur in the docker, etc
For cx_Freeze I make time. ;-)

**Comment by pnabbefeld** [comment]
As on Arch Linux cx-freeze is handled by packages, it would probably be easier with a new beta - I don't know, if there could arise side-effects from upgrading from two different channels, as I'm usually just happily downloading packages.

**Comment by marcelotduarte** [comment]
OK. [Beta 6.8b5 released.](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8b5)

**Comment by pnabbefeld** [comment]
Thank You! At least, I could build meshroom-git now :)

**Comment by pnabbefeld** [comment]
I don't know, if this has sth. to do with cx-freeze, or probably it's specific to meshroom - I'm getting the following error message when starting "Meshroom":

PySide2/__init__.py: Unable to import shiboken2 from /usr/lib/Meshroom-2021.1.0/lib/library.zip, /usr/lib/Meshroom-2021.1.0/lib
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 113, in run
    module_init.run(name + "__main__")
  File "/home/peter/.cache/pikaur/build/meshroom-git/src/meshroom/setupInitScriptUnix.py", line 42, in run
    exec(code, m.__dict__)
  File "meshroom/ui/__main__.py", line 10, in <module>
  File "/home/peter/.cache/pikaur/build/meshroom-git/src/meshroom/meshroom/ui/app.py", line 5, in <module>
    from PySide2.QtCore import Qt, QUrl, Slot, QJsonValue, Property, Signal, qInstallMessageHandler, QtMsgType, QSettings
  File "/home/peter/.local/lib/python3.9/site-packages/PySide2/__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "/home/peter/.local/lib/python3.9/site-packages/PySide2/__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "/home/peter/.local/lib/python3.9/site-packages/shiboken2/__init__.py", line 27, in <module>
    from .shiboken2 import *
ImportError: /usr/lib/Meshroom-2021.1.0/lib/shiboken2/shiboken2.abi3.so: ELF load command address/offset not properly aligned

**Comment by marcelotduarte** [comment]
Apparently is a problem with pyside2 (shiboken2), but can be with patchelf.
What is the version of pyside2 and patchelf?
patchelf --version

**Comment by pnabbefeld** [comment]
$ patchelf --version
patchelf 0.12

extra/pyside2 5.15.2-3 (qt qt5) [Installiert]

**Comment by marcelotduarte** [comment]
Try with patchelf 0.13 (install from sources if necessary https://cx-freeze.readthedocs.io/en/latest/installation.html#others-requirements)
Try to test pyside2 if it working too. sample here https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples/pyside2
Chek if it run in python and in cx-freeze.

**Comment by marcelotduarte** [comment]
I download a vm with archlinux, updated it. Using the same packages for pyside2 and patchelf.
Build cx_freeze with pip and run the tests. Its works.
The error can be in the PKGBUILD you are using. You can remove extra patch. If you are unsuccessful, please post the PKGBUILD here.

**Comment by pnabbefeld** [comment]
I tried to build meshroom-git yesterday, using patchelf 0.13 from community-testing. The "usual chain", i.e. cx-freeze first, then alice-vision-git, last being meshroom-git. Builds without problems. Only error messages on start (btw, much better than when we started: no core dump). The only difference for the alice-vision and meshroom builds to the "standard" PKGBUILD is, I disabled CUDA (because I simply don't have it). In cx-freeze build, I only changed the package version, and of course I'm skipping checksums.

What might be a problem: pyside2 is an Arch Linux standard package (extra/pyside2 5.15.2-3). If it uses cx-freeze, than it uses the old version, which obviously had some bugs. Then I'll probably have to either wait for a new release of cx-freeze on Arch Linux (with the new version), or I'll have to look for someone to help me creating a workaround.

I'll first check for modules depending on pyside2 - a workaround for many packages becoming instable wouldn't be a good idea ...

**Comment by pnabbefeld** [comment]
Just noticed, only meshroom depends on pyside2 (on my local arch installation), and there's a package pyside2-git in the AUR. I'll try to exchange the package and re-build everything else after I've build pyside2, but this will take some time, of course, so don't expect my results early, please.

**Comment by marcelotduarte** [comment]
OK, but the part of cx_Freeze to work with py39 on archlinux is done.
Maybe some tweak with setup for build, like using "bin_includes": "libstdc++.so.6, and/or libgcc_s.so.1
if you run patchelf --print-needed /usr/lib/python3.9/site-packages/shiboken2/shiboken2.*.so you'll see the dependencies. I think that you should have the same version along with your executable to run.

**Comment by pnabbefeld** [comment]
pyside2-git build doesn't work and won't work (if I'd change it to build, it would be for qt6 instead of qt5). I'll have to create a new build file and try to install it.

**Comment by pnabbefeld** [comment]
Thank You for Your hard work! Could You release the current version of cx-freeze, then? Probably to community-testing, because patchelf is not (yet) released to community repository.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.

**Comment by pnabbefeld** [comment]
Still cannot start Meshroom (after compiling meshroom-git, see above). However, if it works for You, this might be a problem with all these AUR and testing builds etc., so it's probably a better idea to wait until Arch Linux includes the various fixes and modifications. Thank You for fixing cx-freeze!

**Comment by marcelotduarte** [comment]
Wait for ArchLinux to update the cx_Freeze package for their distribution. If you have issues, feel free to contact me.
