### ISSUE TITLE
Qt5 Mac  Class NotificationReceiver is implemented in both

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#133]
Originally reported by: **Tao Zhang (Bitbucket: [zhang_tao](https://bitbucket.org/zhang_tao), GitHub: Unknown)**

----------------------------------------

Hi, 
I am trying to use cx_freeze(4.3.4) to make a Mac app.  There are some error showing when I run the app.

```
#!objc[19819]: Class NotificationReceiver is implemented in both /Users/../build/Qt Zoom-0.1.app/Contents/MacOS/./QtWidgets and /opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/QtWidgets. One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x7f805ba811b0) is not the object's thread (0x7f8059740330).
Cannot move to target thread (0x7f805ba811b0)

On Mac OS X, you might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
This application failed to start because it could not find or load the Qt platform plugin "cocoa".

Available platform plugins are: cocoa, minimal, offscreen.

Reinstalling the application may fix this problem.
Abort trap: 6


```

```
#!$ otool -L ./run
./run:
	/opt/local/Library/Frameworks/Python.framework/Versions/3.4/Python (compatibility version 3.4.0, current version 3.4.0)
	/opt/local/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1152.0.0)


```

Do you have any suggestion? Thanks a lot!

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/133

**Comment by anthony-tuininga** [comment]
*Original comment by* **Almar Klein (Bitbucket: [almarklein](https://bitbucket.org/almarklein), GitHub: [almarklein](https://github.com/almarklein))**:

----------------------------------------

For a solution see: https://github.com/ContinuumIO/anaconda-issues/issues/32 

Although right now I am experiencing the problem again (with PySide on Python3.4, on OSX), and the above solutions do not seem to work :(

**Comment by anthony-tuininga** [comment]
*Original comment by* **Almar Klein (Bitbucket: [almarklein](https://bitbucket.org/almarklein), GitHub: [almarklein](https://github.com/almarklein))**:

----------------------------------------

Oh, and my error was due to the fact that there is now a `imageformats` directory, with libaries for a few formats. But apparently these libraries pull in the system Qt libs. Just removing that `imageformats` directory solved it for me.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Tao Zhang (Bitbucket: [zhang_tao](https://bitbucket.org/zhang_tao), GitHub: Unknown)**:

----------------------------------------

Almar, 

Did you mean I need remove system Qt libs?  I used macports to install Qt5 and pyqt5. When I deactivated pyqt5 and Qt5, the packed apps work. 

Is there any possible to remove system Qt PATH in packed bin file, or only select the local path ("./") in apps?

Thanks a lot,

Tao

**Comment by anthony-tuininga** [comment]
*Original comment by* **Almar Klein (Bitbucket: [almarklein](https://bitbucket.org/almarklein), GitHub: [almarklein](https://github.com/almarklein))**:

----------------------------------------

No, please don't remove your system libs. In the very top post there is a list of essentially 2 things you need to do to prevent Qt from using the system Qt libs. This worked for both PySide and PyQt4. Not sure about PyQt5, but you could try.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Tao Zhang (Bitbucket: [zhang_tao](https://bitbucket.org/zhang_tao), GitHub: Unknown)**:

----------------------------------------

Thanks. I put a qt.conf file to apps's Resources. It works now.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by Eyshika** [comment]
@marcelotduarte I still see this issue in my Mac for qt5.
Installed it as 
`pip3 install PyQt5`

**Comment by marcelotduarte** [comment]
@Eyshika Are you use pyQt 5.14.x? Can you test with 5.12.3 to see if you have the same issue?
If you still have issues, can you open a new issue with details, version of pyQt, etc.
