### ISSUE TITLE
5.1: ImportError: No module named 'encodings'

### ISSUE THREAD

**Issue by ghost** [marcelotduarte/cx_Freeze#324]
Linux Debian 9.2 (Stretch) and Alpine 5.6.2

Previous versions are running fine, but cx_Freeze v5.1 doesn't work for me. The freeze phase looks good, but when starting the binary, it aborts with
```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
```

Here the most simple example, it works fine in cx_Freeze v5.0.2:

```
root@debian:~# echo 'print("Hello World")' > hello.py
root@debian:~#
root@debian:~# python3 -V
Python 3.5.3
root@debian:~# pip3 install cx_Freeze==5.1
Collecting cx_Freeze==5.1
Installing collected packages: cx-Freeze
Successfully installed cx-Freeze-5.1
root@debian:~# cxfreeze --silent hello.py
Missing modules:
? __main__ imported from bdb, pdb
? _dummy_threading imported from dummy_threading
? _frozen_importlib imported from importlib, importlib.abc
? _frozen_importlib_external imported from importlib, importlib._bootstrap, importlib.abc
? _winapi imported from subprocess
? _winreg imported from platform
? ce imported from os
? java.lang imported from platform
? msvcrt imported from subprocess
? nt imported from ntpath, os, shutil
? org.python.core imported from copy
? os.path imported from os, pkgutil, py_compile, unittest, unittest.util
? vms_lib imported from platform
? winreg imported from mimetypes, platform
This is not necessarily a problem - the modules may not be needed on this platform.

Copying data from package collections...
Copying data from package email...
Copying data from package encodings...
Copying data from package html...
Copying data from package http...
Copying data from package importlib...
Copying data from package logging...
Copying data from package pydoc_data...
Copying data from package unittest...
Copying data from package urllib...
Copying data from package xml...
root@debian:~# dist/hello
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007fafa406cb40 (most recent call first):
Aborted
root@debian:~#
```

**Comment by johncf** [comment]
I had a similar problem in Windows. For me, it was `codecs` module. I solved it by extracting `codecs.pyc` from `lib/library.zip` directly into `lib/` (along with `_weakrefset.pyc`, `abc.pyc` and `io.pyc` to finally get it to work).

**Comment by johncf** [comment]
Oh, I just found out that this was fixed in `v6`. Currently it's in beta. So do `pip install cx-Freeze==6.0b1` to upgrade to the beta version.

**Comment by anthony-tuininga** [comment]
Yes, this was corrected in 6.x and is now backported to the 5.x branch as well. Please confirm.

**Comment by ghost** [comment]
That's better, but still not usable. The basic hello.py is working now.

But when I use it with some simple python script, I get `ImportError: No module named '__startup__'`.

I'm using this setup.py with the python scripts at https://github.com/ehlers/IOUtools:
```
from cx_Freeze import setup, Executable
setup (
    options = { "build_exe": { "build_exe": "/usr/local/bin"} },
    executables = [ Executable("iou_import"), Executable("iou_export") ]
)
```

This setup works fine with 5.0.2 and 6.0b1.

**Comment by anthony-tuininga** [comment]
I just tried this myself and it worked perfectly -- with both Python 2.7 and 3.6. Can you double check your environment?

**Comment by ghost** [comment]
I'm building it in a fresh docker container with debian 9.1 (stretch), here my log:
[cx_Freeze-v5.x_log.txt](https://github.com/anthony-tuininga/cx_Freeze/files/1485200/cx_Freeze-v5.x_log.txt)

I'm always getting this `ImportError: No module named '__startup__'` error.

In the same environment, only using 5.0.2 and 6.0b1 it works fine.

**Comment by anthony-tuininga** [comment]
Hmm, can you provide the docker command to get the docker container you are using?

Also, since you're running Python 3.5, can you comment out the PyRun_SimpleString command at line 247 in source/bases/Common.c? Perhaps that is causing problems in your configuration -- and that line should not be needed in Python 3, now that I have backported the code to set the path directly in C.

**Comment by ghost** [comment]
I'm starting the docker container with `docker run -ti debian:stretch`, then I'm issuing the following commands:
```
apt-get update
apt-get install python3-dev python3-pip zlib1g-dev git wget vim-tiny

cd
git clone https://github.com/anthony-tuininga/cx_Freeze.git
cd cx_Freeze
git checkout v5.x
vi source/bases/Common.c
python3 setup.py install
cd ..

wget https://raw.githubusercontent.com/ehlers/IOUtools/master/iou_export
wget https://raw.githubusercontent.com/ehlers/IOUtools/master/iou_import
cat > setup.py <<'EOF'
from cx_Freeze import setup, Executable
setup (
    options = { "build_exe": { "build_exe": "/usr/local/bin"} },
    executables = [ Executable("iou_import"), Executable("iou_export") ]
)
EOF

python3 setup.py build
iou_import
```

Your suggestion to comment out the PyRun_SimpleString command is very helpful, now it works. But isn't that needed for python 2?

**Comment by anthony-tuininga** [comment]
That is indeed needed for Python 2, but it isn't for Python 3. I just pushed code to eliminate that for Python 3. I also used the docker image you suggested and tried with Python 2. It doesn't work with the same issue you noted for Python 3 (which does now work with the change I made). I'll look into that.

**Comment by kevinkjt2000** [comment]
I am seeing this error with Python 3 as well
```
└─▪ build/exe.linux-x86_64-3.6/mc-server-status-bot
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f23368501c0 (most recent call first):
Aborted (core dumped)
└─▪ pip freeze | grep cx
cx-Freeze==5.1
```

Upgrading to 6.0b1 fixes this though.

**Comment by anthony-tuininga** [comment]
I just pushed a change through to the v5.x branch that should resolve this issue for everyone. I have confirmed that it works as expected on Debian, Fedora and Windows. Please confirm. Thanks!

**Comment by kevinkjt2000** [comment]
5.1.1 on the v5.x branch seems to fix the issue.

**Comment by anthony-tuininga** [comment]
Thanks for confirming that for me. I'll make a 5.1.1 release next week with this fix included.

**Comment by ghost** [comment]
Tested both with Debian and Alpine, works fine. Thanks a lot.

**Comment by anthony-tuininga** [comment]
Thanks for confirming as well. New release coming up soon!

**Comment by patrickelectric** [comment]
I'm using cx_freeze 5.1-1 and having the same problem.
Build output: http://ix.io/12yO
```
./main 
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fab9b396040 (most recent call first):
[1]    19750 abort (core dumped)  ./main
```

**Comment by chetanjain2099** [comment]
My cx_freeze build is working fine. But after build I get an error like this ( I am using cx_Freeze 5.1.1 ) :
Fatal Python error: Py_Initialize: unable to load the file system codec
Traceback (most recent call last):
  File "C:\Python36\lib\encodings\__init__.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
zlib.error: Error -3 while decompressing data: invalid code lengths set

**Comment by alex-eri** [comment]
Debian 9
Python 3.7 from source
cx-Freeze==6.0b1

Fatal Python error: initfsencoding: Unable to get the locale encoding
zipimport.ZipImportError: can't find module 'encodings'

Current thread 0x00007fb3ce31ce80 (most recent call first):
Аварийный останов

**Comment by LaurentBerder** [comment]
Hi,

I'm working in Python 3.9, with cx_Freeze 6.4.2

Whenever I use cx_Freeze, the processes goes through without issues, but I can't run the exe, with this error:

```
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'G:\src\Application\build\exe.win-amd64-3.9\my_app.exe'
  isolated = 0
  environment = 0
  user site = 1
  import site = 0
  sys._base_executable = 'G:\\src\\Application\\build\\exe.win-amd64-3.9\\my_app.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'G:\\src\\Application\\build\\exe.win-amd64-3.9\\my_app.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'G:\\src\\Application\\build\\exe.win-amd64-3.9\\lib\\library.zip',
    'G:\\src\\Application\\build\\exe.win-amd64-3.9\\lib',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001330 (most recent call first):
<no Python frame>
```

This is the content of my setup.py file:

```
from cx_Freeze import setup, Executable

exe = Executable(
   script = "application_demo.py", # the name of your main python script goes here 
   initScript = None,
   base = None, # if creating a GUI instead of a console app, type "Win32GUI"
   targetName = "my_app.exe"
)

setup(
    name="Autonomie",
    version="1.0",
    description="Assistance à l'autonomie",
    executables = [exe],
    options = {"build_exe": {"packages": ['PyQt5', 'pyqtlet', 'pandas', 'numpy'],
                             "includes": ['os', 'sys', 'encodings', 'requests', 'random']
                             }}
)
```

It seems (right of the bat) like PYTHONHOME and PYTHONPATH do not get found, but I'm not sure whether I should specify this myself.
What's causing this, and how could I solve it?

**Comment by marcelotduarte** [comment]
@LaurentBerder Please open a new issue, as in the closed issue, only I see it.
PYTHONHOME and PYTHONPATH are not set in cx_Freeze.
Put information in this new issue, about the type of python, ie, native, anaconda, etc.
Is this G: drive a net drive? Maybe this is the cause.

**Comment by LaurentBerder** [comment]
Thanks, will do ;-)
