### ISSUE TITLE
ap-ms-win-crt*.dll copied from first folder in PATH

### ISSUE THREAD

**Issue by fireundubh** [marcelotduarte/cx_Freeze#367]
When TortoiseSVN, LLVM, or any installed application that has `api-ms-win-crt*.dll` files is in PATH, cx_Freeze will copy those DLLs from there, regardless of whether `include_msvcr` is set.

For example:
```
copying D:\dev\LLVM\bin\api-ms-win-crt-stdio-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-stdio-l1-1-0.dll
copying D:\dev\LLVM\bin\api-ms-win-crt-string-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-string-l1-1-0.dll
copying D:\dev\LLVM\bin\api-ms-win-crt-heap-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-heap-l1-1-0.dll
copying D:\dev\LLVM\bin\api-ms-win-crt-filesystem-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-filesystem-l1-1-0.dll
copying D:\dev\LLVM\bin\api-ms-win-crt-math-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-math-l1-1-0.dll
copying D:\dev\LLVM\bin\api-ms-win-crt-time-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-time-l1-1-0.dll
copying D:\dev\LLVM\bin\api-ms-win-crt-utility-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-utility-l1-1-0.dll
copying D:\dev\LLVM\bin\api-ms-win-crt-environment-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-environment-l1-1-0.dll
copying D:\dev\LLVM\bin\api-ms-win-crt-runtime-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-runtime-l1-1-0.dll
copying D:\dev\LLVM\bin\api-ms-win-crt-convert-l1-1-0.dll -> E:\projects\modsmith\bin\exe.win-amd64-3.6\lib\api-ms-win-crt-convert-l1-1-0.dll
```

There is a workaround.

For PyCharm users, simply add an empty PATH environment variable to your Run/Debug configuration.

![Environment Variables](https://i.imgur.com/P5DppYP.jpg)

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by sekrause** [comment]
This issue is not solved, I just checked and it still exists in the current Github master branch.

**Comment by marcelotduarte** [comment]
@sekrause You're using Anaconda?

**Comment by sekrause** [comment]
@marcelotduarte No, just a simple Python 3.7 venv.

**Comment by marcelotduarte** [comment]
Finally, I looked at it. PR #973 in main branch.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
