### ISSUE TITLE
ImportError: libopenblasp (cx_Freeze on linux)

### ISSUE THREAD

**Issue by kalumb** [marcelotduarte/cx_Freeze#406]
Hi!
I'm using cx_Freeze to build a project under Linux (Ubuntu x32 16.04, Python3.6). The program uses the NumPy library. After the program is built, all the libraries are placed in the "lib" folder. In the main file, I also added the search path:
sys.path.append (os.path.realpath (os.path.dirname (sys.argv [0])) + "/" + "lib")

When you run the program produces an error:
"ImportError: libopenblasp-r0-135a2122.2.18.so: cannot open shared object file: No such file or directory"
The libopenblasp-r0-135a2122.2.18.so file is located in the lib folder. After moving this library to the program's root directory, the program can not import another library. If all these files are manually moved to the root, the program will work.
What can be done with this?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "ExtensionLoader_numpy_core_multiarray.py", line 23, in <module>
  File "ExtensionLoader_numpy_core_multiarray.py", line 15, in __bootstrap__
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libopenblasp-r0-135a2122.2.18.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "main.py", line 12, in <module>
  File "/usr/local/lib/python3.6/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.6/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libopenblasp-r0-135a2122.2.18.so: cannot open shared object file: No such file or directory
```

**Comment by alex-eri** [comment]
Check `ldd lib...so`. Dependency missed to load (link) library

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by ksaurabh-cadence** [comment]
I am using cx-Freeze==6.1 and I still see the same issue. 

`ImportError: libopenblasp-r0-34a18dc3.3.7.so: cannot open shared object file: No such file or directory`

I am using Python 3.6.1 on RHEL 7. 
The missing libraries are present in numpy.libs folder and looking at the cx_freeze log I see following message 

`copying xxx/lib/python3.6/site-packages/numpy/core/../../numpy.libs/libopenblasp-r0-34a18dc3.3.7.so -> app2/exe.linux-x86_64-3.6/lib/numpy/core/libopenblasp-r0-34a18dc3.3.7.so`

While manually copying the so file into app2/exe.linux-x86_64-3.6/lib solves the issue, but I am not sure why it's copying it into numpy/core folder. Is there a way to make it copy it into app2/exe.linux-x86_64-3.6/lib if that's where the app is finally going to look for so files?
