### ISSUE TITLE
Install doesn’t work on Python 3.7 on Windows.

### ISSUE THREAD

**Issue by xaoseric** [marcelotduarte/cx_Freeze#407]
Installing on Windows 10 64bit with Python 3.7 gives the following error `/cxfreeze-postinstall does not exist`, after reverting back to Python 3.6.6, it installs fine, perhaps it has to do with the path change for Python 3.7 under Windows?

**Comment by fabioparodi** [comment]
Same problem on my side. I have managed to install the wheel:

cx_Freeze-5.1.1-cp37-cp37m-win_amd64.whl

you may find it here:

https://www.lfd.uci.edu/~gohlke/pythonlibs/#cx_freeze

The wheel installs but does not work with python 3.7 due to changes to the bytecode format.
In order to get it working you will need to manually merge this patch: 

https://github.com/anthony-tuininga/cx_Freeze/pull/395/commits/76542754e01d2d4b21c6744c563dda8d5c72b3b2

Which means changing the file C:\Python37\Lib\site-packages\cx_Freeze\freezer.py

**Comment by guettli** [comment]
An official wheel for Python 3.7 for Windows on pypi would be great.

**Comment by mk1novotny** [comment]
For me works: clone repository, checkout v6.0b1, python setup build, python setup install

**Comment by golyalpha** [comment]
Can confirm that installing with pip causes a crash with the cxfreeze-postinstall not found. Also can confirm that cloning the repo, and build-installing it locally works, but it somehow installs cxfreeze scripts with no extension, and they can't be run as scripts in path (even if the extension is added into the PATHEXT variable). Using it as a Distutils extension still works, though I am having issues getting it to work with win10toast.

**Comment by ThiefMaster** [comment]
Could this please be fixed? It's open since 4 months...

**Comment by samld** [comment]
Please fix this! This is a nightmare!

**Comment by anirbanspace** [comment]
Please fix.
Cannot install cx_Freeze

**Comment by sri321** [comment]
any update yet ?

**Comment by forestbelton** [comment]
What needs to be done so this can be fixed?

**Comment by Systemcluster** [comment]
This is fixed in the next release (cx_Freeze 6), which isn't released on PyPy yet. You can install directly from the repository for now: 

    pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master

**Comment by golyalpha** [comment]
Can we get some 3rd party confirmations on that? (Not that I don't trust the devs, let's just see if someone has a slightly more bizarre setup)

**Comment by THB0705** [comment]
Issues are still persisting on my end. Installing directly from repository also throws error code 1

**Comment by sri321** [comment]
Errors still persist

**Comment by francoatmega** [comment]
> For me works: clone repository, checkout v6.0b1, python setup build, python setup install

**After trying a variety of methods, the manual installation worked for me like a charm.**

![image](https://user-images.githubusercontent.com/8761008/51248217-3652be00-196e-11e9-8fb3-0a9179904db3.png)

**Comment by golyalpha** [comment]
@francoatmega Do the included scripts work for you on Windows?

**Comment by francoatmega** [comment]
@golyalpha  I haven't used this included scripts, for my project I used the below:

`from cx_Freeze import setup, Executable
import sys

if sys.platform == "win32":
    base = "Win32GUI"

executables = [
    Executable('../WanBackupService.py', icon="../images/wan-info.ico" ,base = base),
    Executable('../WanBackup.py', icon="../images/wan-info.ico" , base = base),
    Executable('../WanLogServer.py', icon="../images/wan-info.ico" , base = base),
    Executable('../WanUpdater.py', icon="../images/wan-info.ico" , base = base),
    Executable('../MSSQLWinAuth.py', icon="../images/wan-info.ico" , base = base)
]

includefiles = [ '../images' , '../7za.exe' , 'nssm.exe']

setup(name='WanBackup',
      version='1.0.0.8',
      description='Wan Backup',
      executables=executables,
      options = { 'build_exe': { 'include_files': includefiles } }
      )`

**Comment by golyalpha** [comment]
@fabioparodi Yeah, that works, but the scripts are a part of the featureset, so, technically, they should work.

**Comment by acaparroso** [comment]
Hello, If you are still having issues like this, for me running the following command worked:

pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master

Hope it works, spent countless hours trying to install it.

**Comment by arredondo-vidal** [comment]
> Same problem on my side. I have managed to install the wheel:
> 
> cx_Freeze-5.1.1-cp37-cp37m-win_amd64.whl
> 
> you may find it here:
> 
> https://www.lfd.uci.edu/~gohlke/pythonlibs/#cx_freeze
> 
> The wheel installs but does not work with python 3.7 due to changes to the bytecode format.
> In order to get it working you will need to manually merge this patch:
> 
> [7654275](https://github.com/anthony-tuininga/cx_Freeze/commit/76542754e01d2d4b21c6744c563dda8d5c72b3b2)
> 
> Which means changing the file C:\Python37\Lib\site-packages\cx_Freeze\freezer.py

In my case, I unistalled the version Python3.7 32bits and install the Python3.7 64bit version, the wheel installs work for me.

**Comment by r58Playz** [comment]
> Hello, If you are still having issues like this, for me running the following command worked:
> 
> pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master
> 
> Hope it works, spent countless hours trying to install it.

That works great! 😂😂

**Comment by golyalpha** [comment]
Ok, pip-installing from git master works for me now.
Issue: Scripts don't run.
Running `cxfreeze` in PowerShell opens Notepad++ on my PC.

**Comment by PickledBeef** [comment]
pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master

That works!

**Comment by fabioparodi** [comment]
Installs, but then it does not work: the generated executable does not work.
`D:\AGV\build\exe.win-amd64-3.7>main_tcs_service.exe
Traceback (most recent call last):
  File "c:\Python37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "c:\Python37\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "main_tcs_service.py", line 12, in <module>
ModuleNotFoundError: No module named 'tcs_service'`

**Comment by vincent-lg** [comment]
Hello,

Sorry to add yet another comment on an already verbose issue, but here's something developers of cx_Freeze might consider:

    pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master

Works great, I'm happy to say, but unfortunately, on Windows, it creates a bunch of scripts that cannot be used.  The `cxfreeze` script in particular is installed (in `python\scripts`) but without an extension.  The proper file would be `cxfreeze.exe`.  Windows seems reluctant to executing files without extensions.  Can it be fixed before the release of cxFreeze 6?  Not meaning to delay said release, since I would prefer to type:

    pip install cx_Freeze

And tell my user to do so, not giving the complicated command that works.

Thank you in advance, and good luck on cxFreeze 6,

**Comment by mkakpabla** [comment]
Solution here: [https://stackoverflow.com/questions/50686243/cant-install-cx-freeze-or-scipy-for-python-3-7-64-bit](url)

**Comment by anthony-tuininga** [comment]
cx_Freeze 6 has just been released with support for Python 3.7.
