### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by jermaine1ronquillo** [marcelotduarte/cx_Freeze#436]
Running my app will throw an error:

Traceback (most recent call last):
  File "C:\miniconda\envs\portal\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\miniconda\envs\portal\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "data_process.py", line 6, in <module>
  File "c:\data2016\portal\portal_interface\build\exe.win-amd64-3.6\portal_interface.py", line 6, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "C:\miniconda\envs\portal\lib\site-packages\sklearn\preprocessing\__init__.py", line 8, in <module>
    from .data import Binarizer
  File "C:\miniconda\envs\portal\lib\site-packages\sklearn\preprocessing\data.py", line 19, in <module>
    from scipy import stats
  File "C:\miniconda\envs\portal\lib\site-packages\scipy\stats\__init__.py", line 345, in <module>
    from .stats import *
  File "C:\miniconda\envs\portal\lib\site-packages\scipy\stats\stats.py", line 171, in <module>
    from . import distributions
  File "C:\miniconda\envs\portal\lib\site-packages\scipy\stats\distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "C:\miniconda\envs\portal\lib\site-packages\scipy\stats\_continuous_distns.py", line 113, in <module>
    class norm_gen(rv_continuous):
  File "C:\miniconda\envs\portal\lib\site-packages\scipy\stats\_continuous_distns.py", line 175, in norm_gen
    `optimizer` argument is ignored.\n\n""")
  File "C:\miniconda\envs\portal\lib\site-packages\scipy\misc\doccer.py", line 159, in _doc
    start_of_notes = cls_docstring.find(notes_header)
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by sekrause** [comment]
This is very likely an error in your application and has nothing to do with cx_Freeze.

**Comment by jermaine1ronquillo** [comment]
My application is working properly in my environment,  using cx_Freeze will raise the error above.

**Comment by kg-2** [comment]
turn optimizations off when compiling

**Comment by pbesson-invn** [comment]
Hello,

I have the same problem and application is working fine when run from python.

**Comment by marcelotduarte** [comment]
@jermaine1ronquillo @pbesson-invn 
cx_Freeze 6 has been release. Can you try again? Can I close the issue?
If the application uses multiprocessing, I believe there are still problems to solve in cx_Freeze, but adding freeze_support () may solve your case.
See:
https://docs.python.org/3/library/multiprocessing.html?highlight=freeze#multiprocessing.freeze_support

**Comment by pbesson-invn** [comment]
> 
> 
> @jermaine1ronquillo @pbesson-invn
> cx_Freeze 6 has been release. Can you try again? Can I close the issue?
> If the application uses multiprocessing, I believe there are still problems to solve in cx_Freeze, but adding freeze_support () may solve your case.
> See:
> https://docs.python.org/3/library/multiprocessing.html?highlight=freeze#multiprocessing.freeze_support

Application is using threading, subprocess and pyQt but not multiprocessing module explicitly.

Anyhow, I will try version 6 in the upcoming days and let you know.

**Comment by marcelotduarte** [comment]
@pbesson-invn 
Did you succeed with cx_Freeze6?

**Comment by pbesson-invn** [comment]
@marcelotduarte unfortunately I still have the same issue with version 6.0:

![image](https://user-images.githubusercontent.com/8382348/65586103-e0fe9000-df83-11e9-98f2-d7c0c098d4d2.png)

Works when disabling optimizations.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by pbesson-invn** [comment]
Hello @marcelotduarte,

I still encounter the issue. On another project, exception is slightly different though:

```
Traceback (most recent call last):
  File "C:\Workspace\XXXXXX\XXXXXX-tools\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Workspace\XXXXXX\XXXXXX-tools\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "XXXXXX/logger.py", line 11, in <module>
  File "C:\Workspace\XXXXXX\XXXXXX-tools\XXXXXX\devices\daqmx.py", line 19, in <module>
    import nidaqmx
  File "C:\Workspace\XXXXXX\XXXXXX-tools\venv\lib\site-packages\nidaqmx\__init__.py", line 7, in <module>
    from nidaqmx.scale import Scale
  File "C:\Workspace\XXXXXX\XXXXXX-tools\venv\lib\site-packages\nidaqmx\scale.py", line 7, in <module>
    import numpy
  File "C:\Workspace\XXXXXX\XXXXXX-tools\venv\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Workspace\XXXXXX\XXXXXX-tools\venv\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Workspace\XXXXXX\XXXXXX-tools\venv\lib\site-packages\numpy\core\multiarray.py", line 78, in <module>
    def empty_like(prototype, dtype=None, order=None, subok=None, shape=None):
  File "C:\Workspace\XXXXXX\XXXXXX-tools\venv\lib\site-packages\numpy\core\overrides.py", line 203, in decorator
    docs_from_dispatcher=docs_from_dispatcher)(implementation)
  File "C:\Workspace\XXXXXX\XXXXXX-tools\venv\lib\site-packages\numpy\core\overrides.py", line 159, in decorator
    add_docstring(implementation, dispatcher.__doc__)
TypeError: add_docstring() argument 2 must be str, not None
```
Works when disabling optimizations.

**Comment by marcelotduarte** [comment]
If with optimizations disabled it works, probably a issue with the package. The optimizations remove the doc (set __doc__ to None).
I fyou run your project with optimizations enabled in python it runs? Probably not.
