### ISSUE TITLE
Tkinter module not found when launching .exe

### ISSUE THREAD

**Issue by nachovoss** [marcelotduarte/cx_Freeze#567]
A while ago I created a tkinter application that worked fine and compiled with no problems with cx_freeze and worked perfectly.
Today I'm trying to compile another GUI application and it seems to freeze fine(no errors while compiling), but when I execute the .EXE file it says the folowing:
![Capture](https://user-images.githubusercontent.com/38444147/73083995-74ad8200-3ecc-11ea-913a-fe7e9ddc9304.PNG)

hope someone can help!
thanks!

**Comment by nachovoss** [comment]
Fixed by accessing  lib folder from dist folder and changing name Tkinter for tkinter

**Comment by marcelotduarte** [comment]
What version of cx-freeze?
If you try the sample:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/Tkinter
what happens?

**Comment by AceScottie** [comment]
Im having the same issue.
cx_freeze 6.1 installed using pip.
My main project builds with the folder called Tkinter and simply changing it to tkinter fixes the issue.
Issue persistent in 3.7.6 and 3.8.1.
Tested using the setup sample and the issue is not happening there.
I have tried switching from root.mainloop() to a while loop to recreate closely to my project but no difference 
However i believe the root issue is with tkcalendar. 
added to simpleTkApp:
from tkcalendar import Calendar, DateEntry
DateEntry(root).pack()

And it now changes to Tkinter.

Worth taking a look ?

Edit: I have had a lot of issue with Babel in my new env so it might stem from there as tkcalendar has it as a dependency.
Errors:
Bad Magic Numbers (this seemed to stop happening randomly)
locale-data not found (recompiled from github and ran additional setup command)
bable.numbers not found (skipped compile so had to "include" it in the options.

**Comment by marcelotduarte** [comment]
@AceScottie 
In py3x the correct name is tkinter, in old python the name is Tkinter. Maybe the imported tkcalendar was trying to import Tkinter first and confuses cx-freeze.
Try to put a import tkinter before the import tkcalendar, remove the build dir and rebuild.
If you bad magic number errors, try to uninstall the package and install again.

**Comment by AceScottie** [comment]
@marcelotduarte 
I have checked thorough tkcalendar and it has an exception to import Tkinter but always as the second option.

`try:
    import tkinter as tk
    from tkinter import ttk
except ImportError:
    import Tkinter as tk
    import ttk`

And i had the same in my code however i though this might of been an issue so removed the unused import and it didnt change anything.
In the example code provided i added the import below tkinter import so it should be easy to reproduce.

**Comment by marcelotduarte** [comment]
@nachovoss @AceScottie I confirmed the issue. You can use a workaround while my PR was not merged.
I made this patch on the sample to test:

```
diff --git a/cx_Freeze/samples/Tkinter/SimpleTkApp.py b/cx_Freeze/samples/Tkinter/SimpleTkApp.py
index ebb0d41..ff73944 100644
--- a/cx_Freeze/samples/Tkinter/SimpleTkApp.py
+++ b/cx_Freeze/samples/Tkinter/SimpleTkApp.py
@@ -1,6 +1,8 @@
 from tkinter import Tk, Label, Button, BOTTOM
+from tkcalendar import Calendar, DateEntry
 
 root = Tk()
+DateEntry(root).pack()
 root.title('Button')
 Label(text='I am a button').pack(pady=15)
 Button(text='Button').pack(side=BOTTOM)
diff --git a/cx_Freeze/samples/Tkinter/setup.py b/cx_Freeze/samples/Tkinter/setup.py
index ed00562..491496d 100644
--- a/cx_Freeze/samples/Tkinter/setup.py
+++ b/cx_Freeze/samples/Tkinter/setup.py
@@ -18,6 +18,14 @@ base = None
 if sys.platform == 'win32':
     base = 'Win32GUI'
 
+options = {
+    'build_exe': {
+        'packages': ['babel'],
+        'excludes': ['Tkinter'],
+        'silent': True
+    }
+}
+
 executables = [
     Executable('SimpleTkApp.py', base=base)
 ]
@@ -25,5 +33,6 @@ executables = [
 setup(name='simple_Tkinter',
       version='0.1',
       description='Sample cx_Freeze Tkinter script',
-      executables=executables
+      executables=executables,
+      options=options
       )
```

**Comment by marcelotduarte** [comment]
PR merged.
