### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll

### ISSUE THREAD

**Issue by jpeg13** [marcelotduarte/cx_Freeze#739]
Reopening https://github.com/marcelotduarte/cx_Freeze/issues/355 : issue re-appeared with cx_Freeze 6.1 and is still there with 6.2.

The executable built with cx_Freeze fails to launch, without showing any error message when started with double-click or from a Windows `cmd` prompt. When started from a Git Bash shell, the following error message is displayed:

> INTEL MKL ERROR: The specified module could not be found. mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

Configuration:

- Windows 10
- Python 3.8.5 installed from https://www.python.org/
- numpy 1.19.1+mkl installed with pip using wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/
- various python modules installed using pip

A same/similar issue is also observed with Python 3.6.8 or earlier versions of numpy such as e.g. 1.18.4+mkl or 1.19.0+mkl.

I've observed that cx_Freeze includes 3 DLLs `mkl_rt.dll`, `python38.dll`, and `vcruntime140.dll` in the subdirectory `lib\numpy\core` of the build directory, whereas the original installation does not contain any DLL in the subdirectory `site-packages\numpy\core` (all DLLs are in `site-packages\numpy\DLLs`). If I manually remove `mkl_rt.dll` from the subdirectory `lib\numpy\core` of the build directory after building the application with cx_Freeze, the issue disappears and the application works.

**Comment by double0darbo** [comment]
I attempted the fix to help solve another problem, which experienced the same `mkl_intel_thread.dll` error, **https://github.com/marcelotduarte/cx_Freeze/issues/682**. 

I also had to remove the same file in `lib\mkl`, which allowed me to open the .exe from a console, still not the .exe folder. This produced a separate issue than I had seen on #682 .

---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\<>\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\<>\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\<>\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\<>\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\<>\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run
    exec(code,  m.__dict__)
  File "matplotlib_eg.py", line 3, in <module>
  File "C:\<>\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\<>\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\<>\build\exe.win-amd64-3.7\matplotlib_eg.exe"
  * The NumPy version is: "1.18.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.


---------------------------
OK   
---------------------------

**Comment by marcelotduarte** [comment]
@jpeg13 @double0darbo 
cx_Freeze 6.3 has just been released.
Can you check if this has been resolved?

**Comment by marcelotduarte** [comment]
I see an issue with numpy 1.18.3 to 1.19
For now, it has a workaround.
pip install "numpy<1.18.3"

**Comment by jpeg13** [comment]
@marcelotduarte 
I've tested cx_Freeze 6.3:

- The issue is still there with Python 3.6.8 and numpy 1.17.4+mkl (i.e. the .exe does not work, there is a file mkl_rt.dll in lib\numpy\core, and the .exe works if one manually removes this .dll)

- The issue is also still there with Python 3.8.5 and numpy 1.19.2+mkl

- I'm not able to test Python 3.8.5 with numpy+mkl<1.18.3 because I don't have any corresponding .whl available.

**Comment by double0darbo** [comment]
Success! I was able to get this to work after many months. The `pip install "numpy<1.18.3"` and update to cx_freeze 6.5 using `conda update cx_freeze` did the trick. 

Here is the list of dependencies:

Name | Version | Build | Channel
-- | -- | -- | --
atk-1.0 | 2.36.0 | h7222f49_4 | conda-forge
brotlipy | 0.7.0 | py38hab1e662_1001 | conda-forge
ca-certificates | 2020.12.5 | h5b45459_0 | conda-forge
cairo | 1.16.0 | hba8bd2f_1007 | conda-forge
certifi | 2020.12.5 | py38haa244fe_1 | conda-forge
cffi | 1.14.4 | py38hd8c33c5_1 | conda-forge
chardet | 4.0.0 | py38haa244fe_1 | conda-forge
cryptography | 3.3.1 | py38hd8c33c5_1 | conda-forge
cx-logging | 2.2 | pypi_0 | pypi
cx_freeze | 6.5 | py38h294d835_0 | conda-forge
cycler | 0.10.0 | py_2 | conda-forge
epoxy | 1.5.5 | h8d14728_0 | conda-forge
freetype | 2.10.4 | h546665d_0 | conda-forge
fribidi | 1.0.10 | h8d14728_0 | conda-forge
gdk-pixbuf | 2.42.2 | hd590532_2 | conda-forge
gettext | 0.19.8.1 | h1a89ca6_1005 | conda-forge
git | 2.28.0 | 1 | conda-forge
glib | 2.66.4 | he2d232f_1 | conda-forge
gtk3 | 3.24.22 | h2af1af7_1 | conda-forge
hicolor-icon-theme | 0.17 | h57928b3_2 | conda-forge
icu | 68.1 | h0e60522_0 | conda-forge
idna | 2.1 | pyh9f0ad1d_0 | conda-forge
importlib-metadata | 1.7.0 | pypi_0 | pypi
importlib_metadata | 3.4.0 | hd8ed1ab_0 | conda-forge
intel-openmp | 2020.3 | h57928b3_311 | conda-forge
jpeg | 9d | h8ffe710_0 | conda-forge
kiwisolver | 1.3.1 | py38hbd9d945_1 | conda-forge
libblas | 3.8.0 | 16_mkl | conda-forge
libcblas | 3.8.0 | 16_mkl | conda-forge
libclang | 11.0.0 | default_h5c34c98_2 | conda-forge
libffi | 3.3 | h0e60522_2 | conda-forge
libglib | 2.66.4 | h5320221_1 | conda-forge
libiconv | 1.16 | he774522_0 | conda-forge
liblapack | 3.8.0 | 16_mkl | conda-forge
libpng | 1.6.37 | h1d00b33_2 | conda-forge
libtiff | 4.2.0 | hc10be44_0 | conda-forge
lz4-c | 1.9.3 | h8ffe710_0 | conda-forge
m2w64-gcc-libgfortran | 5.3.0 | 6 | conda-forge
m2w64-gcc-libs | 5.3.0 | 7 | conda-forge
m2w64-gcc-libs-core | 5.3.0 | 7 | conda-forge
m2w64-gmp | 6.1.0 | 2 | conda-forge
m2w64-libwinpthread-git | 5.0.0.4634.697f757 | 2 | conda-forge
matplotlib | 3.3.1 | 1 | conda-forge
matplotlib-base | 3.3.1 | py38hfb9ee82_1 | conda-forge
mkl | 2020.1 | 216 |  
msys2-conda-epoch | 20160418 | 1 | conda-forge
numpy | 1.18.2 | pypi_0 | pypi
olefile | 0.46 | pyh9f0ad1d_1 | conda-forge
openssl | 1.1.1i | h8ffe710_0 | conda-forge
pandas | 1.2.0 | py38h4c96930_0 | conda-forge
pango | 1.42.4 | hec34917_5 | conda-forge
pathlib2 | 2.3.5 | py38haa244fe_3 | conda-forge
pcre | 8.44 | ha925a31_0 | conda-forge
pillow | 6.2.2 | pypi_0 | pypi
pip | 20.2.2 | py_0 | conda-forge
pixman | 0.40.0 | h8ffe710_0 | conda-forge
pthread-stubs | 0.4 | hcd874cb_1001 | conda-forge
pycparser | 2.2 | pyh9f0ad1d_2 | conda-forge
pyopenssl | 20.0.1 | pyhd8ed1ab_0 | conda-forge
pyparsing | 2.4.7 | pyh9f0ad1d_0 | conda-forge
pypubsub | 4.0.3 | py_0 | conda-forge
pyqt | 5.12.3 | py38haa244fe_6 | conda-forge
pyqt-impl | 5.12.3 | py38h885f38d_6 | conda-forge
pyqt5-sip | 4.19.18 | py38h885f38d_6 | conda-forge
pyqtchart | 5.12 | py38h885f38d_6 | conda-forge
pyqtwebengine | 5.12.1 | py38h885f38d_6 | conda-forge
pysocks | 1.7.1 | py38haa244fe_3 | conda-forge
python | 3.8.6 | h7840368_4_cpython | conda-forge
python-dateutil | 2.8.1 | py_0 | conda-forge
python_abi | 3.8 | 1_cp38 | conda-forge
pytz | 2020.5 | pyhd8ed1ab_0 | conda-forge
qt | 5.12.9 | h5909a2a_3 | conda-forge
requests | 2.25.1 | pyhd3deb0d_0 | conda-forge
setuptools | 49.6.0 | py38haa244fe_3 | conda-forge
six | 1.15.0 | pyh9f0ad1d_0 | conda-forge
sqlite | 3.34.0 | h8ffe710_0 | conda-forge
tk | 8.6.10 | h8ffe710_1 | conda-forge
tornado | 6.1 | py38h294d835_1 | conda-forge
urllib3 | 1.26.2 | pyhd8ed1ab_0 | conda-forge
vc | 14.2 | hb210afc_2 | conda-forge
vs2015_runtime | 14.28.29325 | h5e1d092_0 | conda-forge
wheel | 0.36.2 | pyhd3deb0d_0 | conda-forge
win_inet_pton | 1.1.0 | py38haa244fe_2 | conda-forge
wincertstore | 0.2 | py38haa244fe_1006 | conda-forge
wxpython | 4.0.7.post2 | py38h6fd17b8_3 | conda-forge
xz | 5.2.5 | h62dcd97_1 | conda-forge
zipp | 3.1.0 | pypi_0 | pypi
zlib | 1.2.11 | h62dcd97_1010 | conda-forge
zstd | 1.4.8 | h4e2f164_1 | conda-forge

Here's the setup.py for completion's sake--notice, I am still struggling with the scipy, as I converted code entirely to numpy; I haven't attempted matplotlib or tkinter interactions yet:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
# Needed for properly encoding setup.py file – 9/5/18
# Sarah's original setup code:
# --include-modules=NAMES
# --ext-list-file=NAME ...name of file in which to place the list of dependent files which were copied into the target directory
from cx_Freeze import setup, Executable
import os, sys, numpy, codecs, matplotlib #, tkinter
# Get the working directory and append it to other files
wd = os.getcwd()
os.environ['TCL_LIBRARY'] = os.path.join(wd, r'tcl\tcl8.6')
os.environ['TK_LIBRARY'] = os.path.join(wd, r'tcl\tk8.6')
# GUI applications require a different base on Windows (the default is for a
# console application).
base = None
if sys.platform == "win32": base = "Win32GUI"
# scipy_path = os.path.join(wd, r'Lib\site-packages\scipy')
build_exe_options = {"includes":   ["numpy",
                                    "codecs"],
                     "include_files":['Library/bin/libiomp5md.dll',
                                      'Library/bin/mkl_intel_thread.dll',
                                      'Library/bin/mkl_sequential.dll'
                                      ]
                     }
setup(
    # This is the final name the executable will have
    name = "pykompute",
    # This is the version you choose
    version = "0.0",
    # This is the date or any other description you wish
    description = "Jan_12_2021",
    options = {"build_exe": build_exe_options},
    # This is the program you created
    executables = [Executable("pykompute.py")]#, base=base)]    
)
```

**Comment by marcelotduarte** [comment]
@double0darbo Thanks for reporting!

**Comment by double0darbo** [comment]
Absolutely! I wanted to draw attention to one more note, as I have an error that arises with including the base in `executables = [Executable("pykompute.py")]#, base=base)]    `. My solution is to not consider it, which has had no noticeable adverse problems of note.

**Comment by jpeg13** [comment]
@marcelotduarte Thanks for releasing cx_Freeze 6.5 and 6.5.1, and more generally for keeping this package alive and maintaining it! I appreciate very much, the fact that this issue remains open should not leave a wrong impression.
I've tested these new releases, unfortunately the issue is still there as far as I can tell:

> I've observed that cx_Freeze includes 3 DLLs mkl_rt.dll, python38.dll, and vcruntime140.dll in the subdirectory lib\numpy\core of the build directory, whereas the original installation does not contain any DLL in the subdirectory site-packages\numpy\core (all DLLs are in site-packages\numpy\DLLs).

I guess there is an issue in the identification of the dependencies of the code in `lib\numpy\core`, however I'm not able to tell whether the issue is in the cx_Freeze, numpy, or mkl code.

My workaround:

> If I manually remove mkl_rt.dll from the subdirectory lib\numpy\core of the build directory after building the application with cx_Freeze, the issue disappears and the application works.

still works with these new releases and I also understand that the solution by @double0darbo (thanks for reporting) works by including missing dependencies of the superfluous dependencies into the application library root directory.

**Comment by marcelotduarte** [comment]
@jpeg13 When I started to contribute to the project it looked like he was going to die because there was a lot missing for py38 and above. For me, it fits very well in my projects, without losing performance, etc. In fact, sometimes I can even improve performance using cython.

> I guess there is an issue in the identification of the dependencies of the code in lib\numpy\core, however I'm not able to tell whether the issue is in the cx_Freeze, numpy, or mkl code.

I know of some problems, but unfortunately, I have done a lot on my own. Anthony left everything in my hands and Ian has contributed a lot, but to keep it running on macOS.
I have a new code for this, but I need to fix some things so that one doesn't keep bugging the other. I will do it!

For now, what I can say is that we have to deal with some workarounds, and one of them is to use numpy==1.18.2

**Comment by jpeg13** [comment]
@marcelotduarte 

> I have a new code for this, but I need to fix some things so that one doesn't keep bugging the other. I will do it!

Great news, I'll be happy to test this new code when available! Using workarounds in the meantime is perfectly fine for me.

**Comment by marcelotduarte** [comment]
@jpeg13 @double0darbo 
With recent patches and changes in hooks of matplotlib, numpy and pandas, I get success building the samples matplotlib and pandas (that use numpy).
The samples are in https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples

I used numpy 1.18.2, 1.19.4 and 1.20.1 to test, in py36, 37, 38, 39 on Windows 10
And used numpy 1.19.5+mkl and py38 only (with cx-freeze 6.5.3 I get errors, with current main branch, I get success).
Tested only with official python.org (not anaconda yet).

Please test it and put a comment.
1) Sources: `pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`
2) Wheels: https://github.com/marcelotduarte/cx_Freeze/suites/2241813794/artifacts/46547164

**Comment by marcelotduarte** [comment]
For conda the hooks is in develop branch:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by marcelotduarte** [comment]
I updated the branch, please rerun:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

Also, with recent changes, you should use --includes-msvcr=true or include it in build_exe option of the setup file if you need vcruntimes in the build.

**Comment by jpeg13** [comment]
@marcelotduarte Thank you for the patches and your effort.

Unfortunately, the issue is still there, using numpy 1.20.1+mkl and Python 3.8.5 under Windows 10. I've tested the following commits:
cdc9041 (develop) with include_msvcr = True
b3b84e7 (main) with include_msvcr = True
c4358e5

There is still a still a superfluous DLL `mkl_rt.dll` in `lib\numpy\core` which leads to a missing dependency. I've analyzed a bit further, this DLL gets included as a dependency of `numpy\core\_multiarray_umath.cp38-win_amd64.pyd`
```
copying (project_dir)\venv\lib\site-packages\numpy\core\_multiarray_umath.cp38-win_amd64.pyd -> (build_dir)\lib\numpy\core\_multiarray_umath.cp38-win_amd64.pyd
copying (project_dir)\venv\lib\site-packages\numpy\dlls\mkl_rt.dll -> (build_dir)\lib\numpy\core\mkl_rt.dll
```
I believe that the target should remain `(build_dir)\lib\numpy\dlls\mkl_rt.dll` instead of `(build_dir)\lib\numpy\core\mkl_rt.dll`

I guess a corresponding mechanism to compute a `dependent_target` is missing in `freezer.py` for `win32` (lines 209--213), similar to what is implemented for the default platform (lines 215--238).

A further cause might be that `mkl_rt.dll` does not return any dependency when passed to `Freezer._GetDependentFiles`, but probably has some. The root cause of this issue might be in the `numpy` code.

**Comment by marcelotduarte** [comment]
With the samples pandas and matplotlib at https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples I can't reproduce the error with MKL anymore. Can you improve the sample for me to test?

> I guess a corresponding mechanism to compute a dependent_target is missing in freezer.py for win32 (lines 209--213), similar to what is implemented for the default platform (lines 215--238).

Loading of Windows DLL is quite different from shared lib in Linux.
I imagine that if you use zip_include_packages=["numpy"] this error get out

**Comment by jpeg13** [comment]
> With the samples pandas and matplotlib at https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples I can't reproduce the error with MKL anymore. Can you improve the sample for me to test?

Surprisingly, the samples pandas and matplotlib also work in my configuration.
After some trying I've been able to reproduce the error by modifying the pyside2 sample with following lines:
```
import numpy as np
window.setWindowTitle("Simple, numpy version: " + str(np.__version__))
```
I also need to remove the `"zip_include_packages"` option from the setup to be able to run this sample after freezing (also without the numpy addition).
So it seems that an interaction between `PySide2` and `numpy` might be the root cause. I suspect the PySide2 examples (there seems to be a `numpy` import in there), but I've not been able to quickly exclude them from the frozen application. I believe we are on the right track.

> Loading of Windows DLL is quite different from shared lib in Linux.
> I imagine that if you use zip_include_packages=["numpy"] this error get out

Unfortunately this does not work but brings interesting new information: the folder `numpy\DLLs` is completely missing from the `numpy` folder in the zipped library and the following files get included into the library root instead of the zipped library:
```
mkl_rt.dll
numpy.core._multiarray_tests.cp38-win_amd64.pyd
numpy.core._multiarray_umath.cp38-win_amd64.pyd
numpy.core._operand_flag_tests.cp38-win_amd64.pyd
numpy.core._rational_tests.cp38-win_amd64.pyd
numpy.core._simd.cp38-win_amd64.pyd
numpy.core._struct_ufunc_tests.cp38-win_amd64.pyd
numpy.core._umath_tests.cp38-win_amd64.pyd
numpy.fft._pocketfft_internal.cp38-win_amd64.pyd
numpy.linalg._umath_linalg.cp38-win_amd64.pyd
numpy.linalg.lapack_lite.cp38-win_amd64.pyd
numpy.random._bounded_integers.cp38-win_amd64.pyd
numpy.random._common.cp38-win_amd64.pyd
numpy.random._generator.cp38-win_amd64.pyd
numpy.random._mt19937.cp38-win_amd64.pyd
numpy.random._pcg64.cp38-win_amd64.pyd
numpy.random._philox.cp38-win_amd64.pyd
numpy.random._sfc64.cp38-win_amd64.pyd
numpy.random.bit_generator.cp38-win_amd64.pyd
numpy.random.mtrand.cp38-win_amd64.pyd
```

**Comment by marcelotduarte** [comment]
@jpeg13 I updated the branch a bit and solved the issue with pyside2 in venv.
For matplotlib, new version is out, and in CI that I use it runs, in msys it runs but doesn't run in venv on win32.
So, maybe you need to downgrade to 3.2.2 or 3.3.4.
pandas and numpy for me it's ok.
Can you test?
There are wheels in this zip file:
https://github.com/marcelotduarte/cx_Freeze/suites/2463907264/artifacts/52943414

**Comment by jpeg13** [comment]
@marcelotduarte I can confirm that the regression introduced in #978 for PySide2 in venv is solved by #1010
The MKL ERROR is still there unchanged (also tested with the latest numpy 1.20.2+mkl)

**Comment by marcelotduarte** [comment]
I didn't understand, previously you stated:
> Surprisingly, the samples pandas and matplotlib also work in my configuration

Now: 
> The MKL ERROR is still there unchanged (also tested with the latest numpy 1.20.2+mkl)

For me the samples works. Here a log from CI:
[logs_733.zip](https://github.com/marcelotduarte/cx_Freeze/files/6303970/logs_733.zip)
Can you put some traceback at least?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Can you check if this has been resolved?

Issue #682 is similar to this issue and the developers have success.

**Comment by jpeg13** [comment]
@marcelotduarte I meant the pyside2 sample, with the modification
```
import numpy as np
window.setWindowTitle("Simple, numpy version: " + str(np.__version__))
```
described above, which used to be affected. Now I can confirm that this sample works with the following venv configuration
```
venv/Scripts/python -m pip list
Package            Version
------------------ ----------
cx-Freeze          6.6
cx-Logging         3.0
importlib-metadata 3.7.3
numpy              1.20.1+mkl
pandas             1.2.3
pip                20.1.1
PySide2            5.15.2
python-dateutil    2.8.1
pytz               2021.1
setuptools         47.1.0
shiboken2          5.15.2
six                1.15.0
zipp               3.4.1
```
However I have a more complex application with following venv configuration
```
venv/Scripts/python -m pip list
Package              Version
-------------------- ----------
attrs                20.3.0
cx-Freeze            6.6
cx-Logging           3.0
cycler               0.10.0
importlib-metadata   3.10.1
kiwisolver           1.3.1
Markdown             3.3.4
matplotlib           3.3.4
numpy                1.20.1+mkl
pandas               1.2.3
Pillow               8.2.0
pip                  21.0.1
pyparsing            2.4.7
PySide2              5.15.2
python-dateutil      2.8.1
pytz                 2021.1
setuptools           54.1.1
shiboken2            5.15.2
six                  1.15.0
zipp                 3.4.1
```
plus some company internal packages, which is still affected by the MKL ERROR.

The frozen application simply does not start without producing any error. If I redirect the output of the application into a file using e.g. `application.exe > out.txt`, the file `out.txt` then contains
> INTEL MKL ERROR: The specified module could not be found. mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

(resp. the corresponding message in the OS language). That's all I get, there is no traceback.

I need to further investigate the differences between the modified pyside2 sample (now working) and the more complex application (still not working), and to come up with a minimal example.
 
> cx_Freeze 6.6 has just been released.

Thanks for your work!

**Comment by jpeg13** [comment]
Follow-up: if I freeze the pyside2 example with the same venv configuration as the "more complex application", adding the version of the main packages to the window title, it still works. The more complex application frozen with the same venv configuration does not work.

In the case of the pyside2 example, no `mkl_rt.dll` gets copied into `lib\numpy\core` by cx_Freeze, in the case of the more complex application, one does. Thus, there must be a function used or at least imported in the more complex application which triggers this dependency inclusion, but I'm not able to find out which one. This issue drives one to despair. But at least there is a simple workaround.

**Comment by marcelotduarte** [comment]
And your workaround:

    If I manually remove mkl_rt.dll from the subdirectory lib\numpy\core of the build directory after building the application with cx_Freeze, the issue disappears and the application works.

**Comment by marcelotduarte** [comment]
@jpeg13 I fixed a regression yesterday. Can you test the new release?
pip install cx-freeze==6.7b3

**Comment by jpeg13** [comment]
@marcelotduarte The issue is unfortunately still there with cx-freeze==6.7b3

**Comment by marcelotduarte** [comment]
@jpeg13 Can you test the new release?
pip install cx-freeze==6.7b5

**Comment by jpeg13** [comment]
@marcelotduarte The issue is still the same with cx-freeze==6.7b5

**Comment by marcelotduarte** [comment]
@jpeg PR #1113 fix this issue.
Can you test the new beta release 6.7b6?
pip install --upgrade cx_Freeze --pre

**Comment by jpeg13** [comment]
@marcelotduarte Many thanks for your efforts. The new beta release 6.7b6 unfortunately still does not fix the issue.

The new mechanism to freeze the MKL DLLs into `lib/numpy_mkl` seems to work properly, however a copy of `mkl_rt.dll` still gets included also into `lib/numpy/core`, causing the reported error. If I manually remove this copy, the frozen application works fine.

Here is an extract of the freezing log output where the superfluous copying happens:

> Copying data from package numpy...
Removing [build_dir]\lib\numpy\DLLs...
Removing [build_dir]\lib\numpy\compat\tests...
Removing [build_dir]\lib\numpy\core\tests...
Removing [build_dir]\lib\numpy\distutils\tests...
Removing [build_dir]\lib\numpy\f2py\tests...
Removing [build_dir]\lib\numpy\fft\tests...
Removing [build_dir]\lib\numpy\lib\tests...
Removing [build_dir]\lib\numpy\linalg\tests...
Removing [build_dir]\lib\numpy\ma\tests...
Removing [build_dir]\lib\numpy\matrixlib\tests...
Removing [build_dir]\lib\numpy\polynomial\tests...
Removing [build_dir]\lib\numpy\random\_examples...
Removing [build_dir]\lib\numpy\random\tests...
Removing [build_dir]\lib\numpy\tests...
Removing [build_dir]\lib\numpy\typing\tests...
copying [source_dir]\venv\lib\site-packages\numpy\core\_multiarray_tests.cp38-win_amd64.pyd -> [build_dir]\lib\numpy\core\_multiarray_tests.cp38-win_amd64.pyd
copying C:\Python38\python38.dll -> [build_dir]\lib\numpy\core\python38.dll
copying [source_dir]\venv\lib\site-packages\numpy\core\_multiarray_umath.cp38-win_amd64.pyd -> [build_dir]\lib\numpy\core\_multiarray_umath.cp38-win_amd64.pyd
copying [source_dir]\venv\lib\site-packages\numpy\DLLs\mkl_rt.dll -> [build_dir]\lib\numpy\core\mkl_rt.dll
...

**Comment by marcelotduarte** [comment]
To help me to solve this, can you put a breakpoint() or print() at load_numpy_* functions at hooks.py at lines 645-667?
Check if excludes are valid.
For me the name of file is core__multiarray_umath.*.pyd for you it has a core_multiarray_umath (minus '_')?
load_numpy_core__multiarray_umath
And in my tests core_multiarray_tests hasn't a dependent to mkl_rl, so you can create an equivalent load_numpy_core_multiarray_tests with the same code to check it.

EDIT:
I tested with version 1.19.5 and 1.20.3+mkl and I see you use
numpy                1.20.1+mkl

Maybe I should use a different approach to exclude the dependencies if these names change frequently.

**Comment by jpeg13** [comment]
@marcelotduarte You are very close to a solution, I believe.
 I've added the following `print` statement

    print('load_numpy_linalg__umath_linalg: finder.constants_module.values = {}, module.file = {}'.format(
        finder.constants_module.values, module.file), file=sys.stderr)
in `load_numpy_core__multiarray_umath` on line 649 and similar statements in `load_numpy_linalg__umath_linalg` and `load_numpy_linalg_lapack_lite`.

I then get the following output (anonymized):
> running build
running build_exe
load_numpy_core__multiarray_umath: finder.constants_module.values = {'BUILD_RELEASE_STRING': None, 'BUILD_COPYRIGHT': None, 'cx_Freeze_version': '6.7b6', 'TCL_LIBRARY': 'lib\\tkinter\\tcl8.6', 'TK_LIBRARY': 'lib\\tkinter\\tk8.6'}, module.file = [source_dir]\venv\lib\site-packages\numpy\core\_multiarray_umath.cp38-win_amd64.pyd
load_numpy_linalg_lapack_lite: finder.constants_module.values = {'BUILD_RELEASE_STRING': None, 'BUILD_COPYRIGHT': None, 'cx_Freeze_version': '6.7b6', 'TCL_LIBRARY': 'lib\\tkinter\\tcl8.6', 'TK_LIBRARY': 'lib\\tkinter\\tk8.6'}, module.file = [source_dir]\venv\lib\site-packages\numpy\linalg\lapack_lite.cp38-win_amd64.pyd
load_numpy_linalg_lapack_lite: finder.constants_module.values = {'BUILD_RELEASE_STRING': None, 'BUILD_COPYRIGHT': None, 'cx_Freeze_version': '6.7b6', 'TCL_LIBRARY': 'lib\\tkinter\\tcl8.6', 'TK_LIBRARY': 'lib\\tkinter\\tk8.6'}, module.file = [source_dir]\venv\lib\site-packages\numpy\linalg\lapack_lite.cp38-win_amd64.pyd
load_numpy_linalg__umath_linalg: finder.constants_module.values = {'BUILD_RELEASE_STRING': None, 'BUILD_COPYRIGHT': None, 'cx_Freeze_version': '6.7b6', 'TCL_LIBRARY': 'lib\\tkinter\\tcl8.6', 'TK_LIBRARY': 'lib\\tkinter\\tk8.6'}, module.file = [source_dir]\venv\lib\site-packages\numpy\linalg\_umath_linalg.cp38-win_amd64.pyd
creating directory [build_dir]\lib
...

and much later as already reported:
> copying [source_dir]\venv\lib\site-packages\numpy\core\_multiarray_tests.cp38-win_amd64.pyd -> [build_dir]\lib\numpy\core\_multiarray_tests.cp38-win_amd64.pyd
copying C:\Python38\python38.dll -> [build_dir]\lib\numpy\core\python38.dll
copying [source_dir]\venv\lib\site-packages\numpy\core\_multiarray_umath.cp38-win_amd64.pyd -> [build_dir]\lib\numpy\core\_multiarray_umath.cp38-win_amd64.pyd
copying [source_dir]\venv\lib\site-packages\numpy\DLLs\mkl_rt.dll -> [build_dir]\lib\numpy\core\mkl_rt.dll
...

So, as you can see, the entry `MKL_PATH` is not set in the `finder.constants_module.values` dictionary at the time when the `load_numpy_core__multiarray_umath` is executed. This is probably because the import of `numpy.core` is completed before the import of `numpy` can be completed and the corresponding hooks thus run in the same order. What is missing is thus a way to let the MKL-related code in the `load_numpy` hook run before `load_numpy_core__multiarray_umath` and similar hooks.

For example, if I manually set an entry

    'constants': ['MKL_PATH="mkl_path"']

in the `build_exe` options (thus forcing a corresponding entry in the `finder.constants_module.values` dictionary from the very beginning), then the `ExcludeDependentFiles` statements in the hooks work and the issue is solved!

Some additional remarks:

- the `'cx_Freeze_version'` entry in the `finder.constants_module.values` dictionary also comes from a `'constants'` entry in the `build_exe` options in my setup script
- I'm also using numpy 1.20.3+mkl in the meantime
- regarding your comment:
  > And in my tests core_multiarray_tests hasn't a dependent to mkl_rl

  I guess the difficulty of this issue is related with this observation. As mentioned in the posts above, I don't get the issue when I run the examples of the cx_Freeze repository, even with some modifications. I get the issue only in a more complex application. My guess is that the dependency of `core_multiarray_???` on `mkl_rt.dll` appears only in a more complex configuration of numpy with other packages, maybe triggered by some interaction between the involved packages. This would explain why the reported "Intel MKL FATAL ERROR" does not happen in the cx_Freeze examples but does happen in more complex configurations. But I've not been able to identify the mechanism triggering this dependency and the involved packages until now, despite many debugging attempts.

**Comment by marcelotduarte** [comment]
Your report helped a lot. Using MKL_PATH to check is incorrect. And some optimizations that I tried fails too.
So I did a new PR #1125 and release cx_Freeze 6.7b7.
Can you test the new beta release?
pip install --upgrade cx_Freeze --pre

**Comment by jpeg13** [comment]
@marcelotduarte PR #1125 and cx_Freeze 6.7b7 solves this issue! Congratulations and many thanks for keeping at this issue.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
pip install --upgrade cx_Freeze
